lear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import   basket, basket_add, basket_remove, ProductsListView



app_name = 'products'


urlpatterns = [
    path('products/', ProductsListView.as_view(), name='products'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),

    path('basket/', basket, name='basket'),
    path('basket/add/<int:product_id>/', basket_add,  name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove,  name='basket_remove')
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UserRegistrationView, login, logout, user_profile, IndexView



app_name = 'users'


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', user_profile, name='profile'),
]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
'class': 'username-input' }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
            'class': 'email-input'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'class': 'password1-input'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password2-input' }))



    class Meta:
        model = User
        fields = ( 'username', 'email', 'password1', 'password2')



class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'l-username-input'}))

    password = forms.CharField(label='Password' ,widget=forms.PasswordInput(attrs={
    'class':  'l-password-input' }))

    class Meta:
        model =User
        fields = ('username', 'password')






class UserProfileForm(UserChangeForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'user-name-block', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'email-block', 'readonly': True}))


    class Meta:
        model = User
        fields = ('username', 'email')

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import auth, messages
from django.urls import reverse, reverse_lazy
from .forms import RegisterUserForm, UserLoginForm, UserProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView




class IndexView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super(IndexView,self).get_context_data()
        context['title'] = 'Fur-Store'
        return context




class UserRegistrationView(CreateView):
    model = User
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url =reverse_lazy('users:login')



#
# def register(request):
#     if request.method == 'POST':
#         form = RegisterUserForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('users:login'))
#         else:
#             print(form.errors)
#     else:
#         messages.error(request, 'Please correct the errors below!')
#         form = RegisterUserForm()
#     context = {'form': form}
#     return render(request, 'register.html', context)




def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:home'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'login.html', context)



@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:home'))



# class UserProfileView(UpdateView):
#     model = User
#     form_class = UserProfileForm
#     template_name = 'profile.html'





@login_required
def user_profile(request):
    username = request.user.username
    email = request.user.email
    form = UserProfileForm()
    context = {
        'title': 'User-Profile',
        'form': form,
        'username' : username,
        'email': email
    }
    return render(request, 'profile.html', context)

users/templates/base.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% block style%}    {% endblock %}
</head>



<body>


<nav class="main-nav">
              <div class="container">
                  <ul class="navbar-nav1">
                      <li class="nav-item"><a href="{% url 'users:home' %}">Home</a></li>
                      <li class="nav-item"><a href="{% url 'products:products' %}">Product</a></li>
                      <li class="nav-item"><a href="{% url 'products:basket' %}">Basket</a></li>
                      <li class="nav-item"><a href="{% url 'users:profile' %}">Profile</a></li>
                      <li class="nav-item"><a href="{% url 'users:register' %}">Register</a></li>
                      <li class="nav-item"><a href="{% url 'users:login' %}">LogIN</a></li>
                      <li class="nav-item"><a href="{% url 'users:logout' %}" >Logout</a></li>
                  </ul>
            </div>
          </nav>
<hr>

{% block content %}


{% endblock %}

</body>
</html>

users/templates/index.html
{% extends 'base.html' %}

    {% load static %}


    {% block style%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index_css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_css/base.css' %}">
{% endblock %}



    <title>Title</title>





{% block content %}

<body>




<h1>Main Page</h1>

<hr>


{% if  user.is_authenticated %}
                    <h2>You are true auth pidarok</h2>
            {%  else %}
                    <h2>You are fucking skinny bich</h2>
{% endif %}




</body>
{% endblock %}

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>LogIN</title>
            <link rel="stylesheet" type="text/css" href="{% static 'css/users_css/auth.css' %}">

</head>
<body>
<section class="register-section">
<div class="form-box">
<div class="form-value">
<form  action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
    <h2>Login</h2>



                <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                                {{ form.username }}
                    <label>Username</label>
                </div>


                            <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                {{ form.password }}

                        <label>Password</label>
                    </div>


                        <button>Log in</button>

                    <div class="register">
                        <p>Don't have an account? <a href="{% url 'users:register' %}">Register</a></p>
                    </div>

</form>
</div>
</div>
</section>

</body>
</html>

users/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ title }}</h1>
<hr>
<a href="{% url 'products:basket' %}">Basket</a>
<br>
<br>
<br>




{% if  user.is_authenticated %}

    <div class="profile-info">
        <div class="user-name-block">
                    <label>Username: </label>
            {{ username }}
        </div>
    <br>

        <div class="email-block">
            <label>Email:  </label>
            {{ email }}
        </div>

    </div>
<hr>
<div class="basket-section">
    <h2>Basket</h2>
</div>


{% endif %}








</body>
</html>

users/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Register</title>
            <link rel="stylesheet" type="text/css" href="{% static 'css/users_css/auth.css' %}">

</head>
<body>
<section class="register-section">
        <div class="form-box">
            <div class="form-value">
                <form action="{% url 'users:register' %}" method="post">
                        {% csrf_token %}
                    <h2>Creating Account</h2>




                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                         {{ form.username }}
                        <label>Username</label>
                    </div>



                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                        {{ form.email }}
                        <label>Email</label>
                    </div>



                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        {{ form.password1 }}
                        <label>Password</label>
                    </div>


                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        {{ form.password2 }}
                        <label>Confirm Password</label>
                    </div>




                    <div class="forget">
                        <label><a href="{% url 'users:login' %}">Have an account? Login</a></label>
                    </div>

                                        <button>Log in</button>


                </form>
            </div>
        </div>
    </section>

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>