lear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import   basket, basket_add, basket_remove, ProductsListView



app_name = 'products'


urlpatterns = [
    path('products/', ProductsListView.as_view(), name='products'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),

    path('basket/', basket, name='basket'),
    path('basket/add/<int:product_id>/', basket_add,  name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove,  name='basket_remove')
]

products/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class ProductCategory(models.Model):

    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return  self.name




class Product(models.Model):

    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)


    def __str__(self):
        return (f"Product: {self.name} | Category: {self.category.name},"
                f" Price: {self.price}, Description: {self.description}")



class Basket(models.Model):

    user = models.ForeignKey( to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Basket for {self.user} | Product: {self.product.name}"

    def sum(self):
        return self.product.price * self.quantity

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.sum() for basket in baskets)


    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import ProductCategory,  Product, Basket
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView



class ProductsListView(ListView):
    model = Product
    template_name = 'products/product.html'
    paginate_by = 3


    def get_queryset(self):
        queryset = super(ProductsListView, self ).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['title'] = 'Store - catalog'
        context['categories'] = ProductCategory.objects.all()
        return context





# def products(request, category_id=None,page_number=1):
#
#     # filter products by category_id
#     products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
#
#     ## product paginator help us to display the required amount of products on each page
#     per_page = 3
#     paginator = Paginator(products, per_page)
#     products_paginator = paginator.page(page_number)
#
#     context = {
#         'title': 'Store-Catalog',
#         'categories': ProductCategory.objects.all(),
#         'products': products_paginator,
#     }
#     return render(request, 'products/product.html', context)




@login_required
def basket(request):
    user = request.user

    context = {
                'title': 'Store-Basket',
                'basket': Basket.objects.filter(user=request.user)
            }

    return render(request, 'products/basket.html', context)



@login_required
def basket_add(request, product_id):

    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)

    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/basket.html
{% extends 'base.html' %}
{% load static %}



{% load static %}

<title>{{ title }}</title>


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base_css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/basket_css/basket.css' %}">
{% endblock %}



{% block content %}

<h1>Basket</h1>
    {% for bas in basket %}
    <h2>Price: {{ bas.total_sum }}</h2>
                            <p>Quantity: {{ bas.total_quantity }}</p>
                            {% endfor %}
<hr>



                        <div class="product-row">
                                {% for bas in  basket %}
                            <div class="col-md-3">
                                <div class="product-page-card">
                                    <div class="product-card-body">
                                        <h2 class="product-card-title text-center">   {{ bas.product.name }}</h2>
                                        <p class="product-card-text text-center">{{  bas.product.description }}</p>
                                        <h5 class="text-center">{{ bas.sum }} grn</h5>
                                        <h5 class="text-center">{{ bas.quantity }}</h5>
                                        <div class="product-btn">
                                            <button type="button">Buy</button>
                                            <br>
                                            <a href="{% url 'products:basket_remove' bas.id %}">Delate</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {% endfor %}





                    </div>
{% endblock %}

products/templates/products/payment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Form</title>
</head>
<body>


<br>

<label>Your name</label>
<br>
<input></input>


<br>

<label>Your surname</label>
<br>
<input></input>


<br>

<label>Your email</label>
<br>
<input></input>








</body>
</html>

products/templates/products/product.html
{% extends 'base.html' %}
{% load static %}


    <title>{{ title  }}</title>



{% block style %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/base_css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/products_css/products.css' %}">
    {% endblock %}






{% block content %}

<body>

<h2>Product Page</h2>

<div class="list-group">
    <h2>Categories: </h2>
{% for category in categories %}
    <a href="{% url 'products:category' category.id %}">{{ category.name }}</a>
    {% endfor  %}
</div>

<hr>


<div class="product-row">
    {% for product in object_list %}

    <div class="col-md-3">
        <div class="product-page-card">
            <div class="product-card-body">
                <img class="card-image" src="{{ product.image.url }}">
                <h2 class="product-card-title text-center">{{ product.name }}</h2>
                <p class="product-card-text text-center">{{ product.description  }}</p>
                <h5 class="text-center">{{ product.price }}</h5>
                <div class="product-btn">
                    <a href="{% url 'products:basket_add' product.id %}">Add to busket</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% if  is_paginated %}
<nav class="page-btn">

    <ul>
        <li class="page-item {% if not page_object.has_previous %} disabled {% endif %}">
            <a  class="page-link"
                href="{% if page_object.has_previous %} {% url 'products:paginator' page_object.previous_page_number %} {% else %} # {% endif %}"
                tabindex="-1" aria-disabled="true">Previous</a>
        </li>


{% for page in paginator.page_range %}
    <li>
        <a href="{% url 'products:paginator' page %}">
            {{  page }}
        </a>
    </li>
{% endfor  %}

        <li class="page-item {% if not page_object.has_next %} disabled {% endif %}">
            <a class="page-link"
               href="{% if page_object.has_next %} {% url 'products:paginator' page_object.next_page_number %}  {% else %} # {% endif %}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}


</body>

{% endblock %}